### ISSUE TITLE
boost-cpp only in run, not host. Intended?

### ISSUE THREAD

**Issue by xhochy** [conda-forge/ros-roscpp-feedstock#5]
The `meta.yaml` only has `boost-cpp` in `run` but not in `host` and thus breaks the migration bot in https://github.com/conda-forge/ros-rostest-feedstock/pull/3. Is this intended here or should we fix the recipe?

**Comment by wolfv** [comment]
I am fixing the recipe! thanks for your hard work!

**Comment by xhochy** [comment]
Thanks!
